name: speakeasy
description: Open source version of tabu
version: 1.5.1+25

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: 6.0.0
  flutter_launcher_icons: 0.13.1
  soundpool: 2.4.1
  url_launcher: 6.3.0
  get: 4.6.6
  blinking_text: 1.0.4
  vibration: 1.9.0
  auto_size_text: 3.0.0
  wakelock_plus: 1.2.5
  google_fonts: 6.2.1
  simple_animations: 5.0.2
  page_transition: 2.1.0
  fluttertoast: 8.2.6
  easy_localization: 3.0.7
  in_app_review: 2.0.9
  shared_preferences: 2.2.3
  flutter_svg: 2.0.10+1
  package_info: 2.0.2
  in_app_purchase: 3.2.0
  locale_emoji: 0.2.1
  flutter_localized_locales: 2.0.5
  restart_app: 1.2.1
  flex_color_scheme: 7.3.1
  freezed_annotation: 2.4.3
  json_annotation: 4.9.0
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  animated_emoji: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: 2.4.11
  custom_lint: 0.6.4
  freezed: 2.5.2
  json_serializable: 6.8.0
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10
  very_good_analysis: 6.0.0

flutter_launcher_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/words/it/
    - assets/words/en/
    - assets/sounds/
    - assets/icons/
    - assets/lang/
    # animated emoji
    - packages/animated_emoji/lottie/partyPopper.json
    - packages/animated_emoji/lottie/neutralFace.json

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf